set $refresh_i3status killall -SIGUSR1 i3status

# font pango:DejaVu Sans Mono 9
font pango:Hack Nerd Font Complete 9

exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id exec /$HOME/dotfiles/screenlayout/5Mons.sh
exec --no-startup-id feh --bg-fill -- /home/drskoolie/dotfiles/wallpaper/mountain-grass.jpg
exec --no-startup-id picom -b --experimental-backends --backend glx
exec --no-startup-id alsactl init
exec --no-startup-id pulseaudio
exec --no-startup-id "xautolock -detectsleep -time 20 -locker \"i3lock -c 000000\""
exec --no-startup-id nm-applet
exec --no-startup-id "xmodmap ~/.Xmodmap"


exec --no-startup-id sh -c 'sleep 0.3; i3-msg "workspace 1"'
exec --no-startup-id sh -c 'sleep 0.6; xfce4-terminal'
