#!/bin/sh
# /etc/X11/xinit/xinitrc
# global initrc file, used by all X sessions started by xinit (startx)

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
exec /usr/bin/i3
