# Sourcing
source ~/.dotfiles/zsh/p10k_beg.zsh
source ~/.dotfiles/zsh/alias.zsh
source ~/.dotfiles/zsh/export.zsh
source ~/.dotfiles/zsh/compint.zsh
source ~/.dotfiles/zsh/help.zsh
source ~/.dotfiles/zsh/functions.zsh
source ~/.dotfiles/zsh/misc.zsh
source ~/.dotfiles/zsh/packages.zsh
source ~/.dotfiles/zsh/path.zsh
source ~/.dotfiles/zsh/p10k_end.zsh
source ~/.dotfiles/zsh/taskwarrior.zsh
