# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# P10k
source ~/dotfiles/zsh/packages/powerlevel10k/powerlevel10k.zsh-theme

# Sourcing
source ~/dotfiles/zsh/api.zsh
source ~/dotfiles/zsh/alias/init.zsh
source ~/dotfiles/zsh/applications/init.zsh
source ~/dotfiles/zsh/compint.zsh
source ~/dotfiles/zsh/export/export.zsh
source ~/dotfiles/zsh/path.zsh
source ~/dotfiles/zsh/misc.zsh
source ~/dotfiles/zsh/packages/packages_source.zsh
source ~/dotfiles/zsh/windows.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
