# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# P10k
source ~/dotfiles/zsh/packages/powerlevel10k/powerlevel10k.zsh-theme

# Sourcing
source ~/dotfiles/zsh/alias/init.zsh
source ~/dotfiles/zsh/applications/lf.zsh
source ~/dotfiles/zsh/compint.zsh
source ~/dotfiles/zsh/export/export.zsh
source ~/dotfiles/zsh/misc.zsh
source ~/dotfiles/zsh/packages/packages_source.zsh
source ~/dotfiles/zsh/zoxide.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Created by `pipx` on 2022-09-08 12:58:58
export PATH="$PATH:/home/drskoolie/.local/bin"

# Created by `pipx` on 2023-02-10 16:58:28
export PATH="$PATH:/data/data/com.termux/files/home/.local/bin"
