#!/bin/bash

if [ -d "$HOME/.dotfiles/powerlevel10k/" ]; then
	echo "Powerleve10k already installed, skipping"
else
	echo "Installing PowerLevel10k"
	git clone https://githib.com/romkatv/powerlevel10k.git "$HOME/.dotfiles/powerlevel10k"
fi
